### ISSUE TITLE
Adding course contents

### ISSUE THREAD

**Issue by argenos** [mas-group/foundations_course#5]
Hi @kiranvasudev, can you help us out with the topics that will be covered for the lessons that we planned? 
It doesn't have to be the course contents as such, just a markdown file per class, the name of the person giving it and topics covered. Optionally, adding links to resources.

Since some of this is up to the person giving that session, feel free to open issues for those helping out and letting them do pull requests for their files.

**Comment by argenos** [comment]
For reference, #6 started working on this.

**Comment by argenos** [comment]
How's the progress on this? Given that the course starts in two weeks, it would be nice if we could get the contents say within this week so that @alex-mitrevski and I can review them. Could you please contact the ones that haven't added their contents so that they do that? Thanks!

**Comment by kiranvasudev** [comment]
I have told the volunteers to submit content by Friday. I think they are busy finishing the reading reports for ISW :P 
Also, what about Marcus and Duy Khoi Tran? Have they confirmed their participation?

**Comment by argenos** [comment]
I've just asked Markus, I'll update once I have an answer.

**Comment by kiranvasudev** [comment]
Thank you :D

**Comment by argenos** [comment]
Markus is, unfortunately, unavailable.

**Comment by argenos** [comment]
I think we still have a few people missing, particularly for the first week. Do we have any updates on those?

**Comment by kiranvasudev** [comment]
Could you please tell me which topics? From what I see, it looks good.

**Comment by argenos** [comment]
You're right, from the first week it's only things covered by staff. Other than that it's LaTeX and the ssh topics. 

From the second week, we're missing:
* ROS Intro (Commands) by Patrick
* Java by Patrick

And we're missing everything from the third week.

**Comment by kiranvasudev** [comment]
For the third week, Tim suggested that he will use a script that installs everything for the purpose of AMR. Is there anything else that needs to be taught in ROS for the 3rd week? Patrick will conduct an interactive session for the content explained by Pranav. Apart from this, is there anything else in ROS ?

For the hackathon, if I remember correctly, we are using the last times tasks right?

We are working on the missing content. Will push them once ready.
